spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: ecommercefinal
      host: localhost
      port: 27017
#      uri: mongodb://localhost:27017/ecommercefinal

server:
  port: 8080
